name: Monitoraggio Prezzi Energia

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Configurazione Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installazione librerie
        run: pip install requests beautifulsoup4

      - name: Verifica posizione file
        run: ls -R

      - name: Esecuzione script
        run: python rilevazione_dati.py

      - name: Salvataggio risultati
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add storico_prezzi.csv
          git commit -m "Aggiornamento prezzi: $(date)" || exit 0
          git push
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add storico_prezzi.csv
          git commit -m "Update prezzi $(date)" || exit 0
          git push
