name: Monitoraggio Prezzi Energia

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Configurazione Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installazione librerie
        run: pip install requests beautifulsoup4

      - name: Esecuzione Script
        run: |
          # Cerchiamo solo i FILE (-type f) che finiscono esattamente con .py
          SCRIPT_PATH=$(find . -type f -name "rilevazione_dati.py" | head -n 1)
          echo "Sto eseguendo il file trovato in: $SCRIPT_PATH"
          python "$SCRIPT_PATH"

      - name: Salvataggio risultati
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          # Cerca i file CSV e li aggiunge individualmente
          find . -name "*.csv" -exec git add {} +
          git commit -m "Aggiornamento prezzi: $(date)" || exit 0
          git push
